libjson-c: disable libbsd
libjson-c is happy to pick up libbsd both on the host and target.
Reproducible with

make package/libbsd/compile;make package/libjson-c/compile

Also fixes host compilation on Arch Linux for a similar reason.
Undefined reference to arc4random.

Fixes: f3a198697f60 ("libjson-c: update to 0.16")
Acked-by: Thomas Huehn thomas.huehn@hs-nordhausen.de
Acked-by: Nick Hainke vincent@systemli.org
Signed-off-by: Rosen Penev <rosenp@gmail.com>